### PR TITLE
Removed unused imports

### PR DESCRIPTION
**Pull request by UP929312**

### CODE REVIEW

**Review by TheTechRobo — CHANGES_REQUESTED** [review]
That'll only work when 2.0 is released.

When 2.0 is merged into master, you can merge it, but for now it won't work since python 2 is supported in 1.x.

**Comment by rsalmei** [comment]
Hey @UP929312, thank you.
But yeah, those are actually needed, and no IDE should report them as unused, did yours warned you?
Take for example the `print_function` __future__, it is extensively used, why did you think it was not used?

**Comment by TheTechRobo** [comment]
@rsalmei 

> extensively used

In python 2.x yes, so I'm assuming it'll work fine once version 2.0 is released ?? Correct me if im wrong.

**Comment by rsalmei** [comment]
Hey @TheTechRobo,
Yes, in python 2 they are **needed**, in python 3 they are **ignored**, so no harm done.
After 2.0 release they won't even exist, since I already removed them in the new code.

**Comment by TheTechRobo** [comment]
Should this PR be closed?

**Comment by rsalmei** [comment]
Yes! 👍

**Pull request closed without merging**
